---
- hosts: all
  sudo: true
  gather_facts: no
  # remote_user: root
  vars:
    document_root: /vagrant
  pre_tasks:    
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: update apt cache
      apt: update_cache=yes

    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'


  roles:    
     - hadoop
     - role: geerlingguy.java
       when: "ansible_os_family == 'Debian'"
       java_packages:
         - openjdk-8-jdk
